version: "3"

tasks:
  go:lint:
    cmd: golangci-lint run

  go:lint:fix:
    cmd: golangci-lint run --fix

  go:format:
    cmds:
      - go tool gofumpt -l -w .
      - go tool goimports -l -w .

  go:test:
    cmd: go test ./internal/...

  go:tidy:
    cmd: go mod tidy

  run:server:
    cmd: go run cmd/server/main.go

  run:front:
    dir: frontend
    cmd: npm run dev

  build:server:
    cmd: go build -o server cmd/server/main.go

  build:front:
    dir: frontend
    cmd: npm run build

  ts:lint:
    dir: frontend
    cmd: npm run lint

  ts:lint:fix:
    dir: frontend
    cmd: npm run lint:fix

  ts:format:
    dir: frontend
    cmd: npm run format

  ts:format:check:
    dir: frontend
    cmd: npm run format:check

  md:format:
    cmd: npx prettier --write "docs/**/*.md"

  md:lint:
    cmds:
      - npx markdownlint-cli --disable MD024 MD033 MD013 -- "docs/**/*.md"
      - lychee --exclude-path frontend *.md docs/**/*.md
