// Code generated by ogen, DO NOT EDIT.

package ogenapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateProject implements createProject operation.
//
// Создаёт новый проект с конфигурацией пайплайна.
//
// POST /api/v1/projects
func (UnimplementedHandler) CreateProject(ctx context.Context, req *ProjectCreate) (r *CreateProjectCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateProjectRun implements createProjectRun operation.
//
// Создаёт новый запуск пайплайна для указанного
// проекта.
//
// POST /api/v1/projects/{project_id}/runs
func (UnimplementedHandler) CreateProjectRun(ctx context.Context, params CreateProjectRunParams) (r *CreateProjectRunCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProject implements getProject operation.
//
// Возвращает полную информацию о проекте по его
// идентификатору.
//
// GET /api/v1/projects/{project_id}
func (UnimplementedHandler) GetProject(ctx context.Context, params GetProjectParams) (r *Project, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProjectRun implements getProjectRun operation.
//
// Возвращает детальную информацию о конкретном
// запуске проекта.
//
// GET /api/v1/projects/{project_id}/runs/{run_id}
func (UnimplementedHandler) GetProjectRun(ctx context.Context, params GetProjectRunParams) (r *ProjectRun, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProjectRuns implements getProjectRuns operation.
//
// Возвращает список всех запусков для указанного
// проекта.
//
// GET /api/v1/projects/{project_id}/runs
func (UnimplementedHandler) GetProjectRuns(ctx context.Context, params GetProjectRunsParams) (r *GetProjectRunsOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProjects implements getProjects operation.
//
// Возвращает список всех проектов в системе.
//
// GET /api/v1/projects
func (UnimplementedHandler) GetProjects(ctx context.Context) (r *GetProjectsOK, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateProject implements updateProject operation.
//
// Обновляет конфигурацию существующего проекта.
//
// PUT /api/v1/projects/{project_id}
func (UnimplementedHandler) UpdateProject(ctx context.Context, req *ProjectUpdate, params UpdateProjectParams) error {
	return ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
