// Code generated by ogen, DO NOT EDIT.

package ogenapi

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateProjectOperation    OperationName = "CreateProject"
	CreateProjectRunOperation OperationName = "CreateProjectRun"
	GetProjectOperation       OperationName = "GetProject"
	GetProjectRunOperation    OperationName = "GetProjectRun"
	GetProjectRunsOperation   OperationName = "GetProjectRuns"
	GetProjectsOperation      OperationName = "GetProjects"
	UpdateProjectOperation    OperationName = "UpdateProject"
)
