// Code generated by ogen, DO NOT EDIT.

package ogenapi

import (
	"fmt"
	"time"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type CreateGlobalEnvVarCreated struct {
	// Уникальный идентификатор созданной переменной.
	ID OptUint `json:"id"`
}

// GetID returns the value of ID.
func (s *CreateGlobalEnvVarCreated) GetID() OptUint {
	return s.ID
}

// SetID sets the value of ID.
func (s *CreateGlobalEnvVarCreated) SetID(val OptUint) {
	s.ID = val
}

type CreateProjectCreated struct {
	// Уникальный идентификатор созданного проекта.
	ID OptUint `json:"id"`
}

// GetID returns the value of ID.
func (s *CreateProjectCreated) GetID() OptUint {
	return s.ID
}

// SetID sets the value of ID.
func (s *CreateProjectCreated) SetID(val OptUint) {
	s.ID = val
}

type CreateProjectRunCreated struct {
	// Уникальный идентификатор созданного запуска.
	ID OptUint `json:"id"`
}

// GetID returns the value of ID.
func (s *CreateProjectRunCreated) GetID() OptUint {
	return s.ID
}

// SetID sets the value of ID.
func (s *CreateProjectRunCreated) SetID(val OptUint) {
	s.ID = val
}

// DeleteGlobalEnvVarNoContent is response for DeleteGlobalEnvVar operation.
type DeleteGlobalEnvVarNoContent struct{}

// Переменная окружения — именованная пара
// «ключ-значение» для передачи конфигурации в скрипты
// пайплайна.
// Ref: #/components/schemas/EnvironmentVariable
type EnvironmentVariable struct {
	// Уникальный идентификатор переменной.
	ID OptUint `json:"id"`
	// Дата и время создания переменной.
	CreatedAt OptDateTime `json:"created_at"`
	// Дата и время последнего изменения значения.
	UpdatedAt OptDateTime `json:"updated_at"`
	// Ссылка на проект (null для глобальных переменных).
	ProjectID OptNilUint `json:"project_id"`
	// Имя переменной окружения (например, DATABASE_URL, API_KEY).
	Name string `json:"name"`
	// Значение переменной окружения.
	Value string `json:"value"`
	// Флаг использования других переменных (формат ${VAR_NAME}).
	UsesOtherVariables OptBool `json:"uses_other_variables"`
}

// GetID returns the value of ID.
func (s *EnvironmentVariable) GetID() OptUint {
	return s.ID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *EnvironmentVariable) GetCreatedAt() OptDateTime {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *EnvironmentVariable) GetUpdatedAt() OptDateTime {
	return s.UpdatedAt
}

// GetProjectID returns the value of ProjectID.
func (s *EnvironmentVariable) GetProjectID() OptNilUint {
	return s.ProjectID
}

// GetName returns the value of Name.
func (s *EnvironmentVariable) GetName() string {
	return s.Name
}

// GetValue returns the value of Value.
func (s *EnvironmentVariable) GetValue() string {
	return s.Value
}

// GetUsesOtherVariables returns the value of UsesOtherVariables.
func (s *EnvironmentVariable) GetUsesOtherVariables() OptBool {
	return s.UsesOtherVariables
}

// SetID sets the value of ID.
func (s *EnvironmentVariable) SetID(val OptUint) {
	s.ID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *EnvironmentVariable) SetCreatedAt(val OptDateTime) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *EnvironmentVariable) SetUpdatedAt(val OptDateTime) {
	s.UpdatedAt = val
}

// SetProjectID sets the value of ProjectID.
func (s *EnvironmentVariable) SetProjectID(val OptNilUint) {
	s.ProjectID = val
}

// SetName sets the value of Name.
func (s *EnvironmentVariable) SetName(val string) {
	s.Name = val
}

// SetValue sets the value of Value.
func (s *EnvironmentVariable) SetValue(val string) {
	s.Value = val
}

// SetUsesOtherVariables sets the value of UsesOtherVariables.
func (s *EnvironmentVariable) SetUsesOtherVariables(val OptBool) {
	s.UsesOtherVariables = val
}

// Данные для создания переменной окружения.
// Ref: #/components/schemas/EnvironmentVariableCreate
type EnvironmentVariableCreate struct {
	// Имя переменной окружения.
	Name string `json:"name"`
	// Значение переменной окружения.
	Value string `json:"value"`
	// Флаг использования других переменных (формат ${VAR_NAME}).
	UsesOtherVariables OptBool `json:"uses_other_variables"`
}

// GetName returns the value of Name.
func (s *EnvironmentVariableCreate) GetName() string {
	return s.Name
}

// GetValue returns the value of Value.
func (s *EnvironmentVariableCreate) GetValue() string {
	return s.Value
}

// GetUsesOtherVariables returns the value of UsesOtherVariables.
func (s *EnvironmentVariableCreate) GetUsesOtherVariables() OptBool {
	return s.UsesOtherVariables
}

// SetName sets the value of Name.
func (s *EnvironmentVariableCreate) SetName(val string) {
	s.Name = val
}

// SetValue sets the value of Value.
func (s *EnvironmentVariableCreate) SetValue(val string) {
	s.Value = val
}

// SetUsesOtherVariables sets the value of UsesOtherVariables.
func (s *EnvironmentVariableCreate) SetUsesOtherVariables(val OptBool) {
	s.UsesOtherVariables = val
}

// Данные для обновления переменной окружения.
// Ref: #/components/schemas/EnvironmentVariableUpdate
type EnvironmentVariableUpdate struct {
	// Имя переменной окружения.
	Name string `json:"name"`
	// Значение переменной окружения.
	Value string `json:"value"`
	// Флаг использования других переменных (формат ${VAR_NAME}).
	UsesOtherVariables OptBool `json:"uses_other_variables"`
}

// GetName returns the value of Name.
func (s *EnvironmentVariableUpdate) GetName() string {
	return s.Name
}

// GetValue returns the value of Value.
func (s *EnvironmentVariableUpdate) GetValue() string {
	return s.Value
}

// GetUsesOtherVariables returns the value of UsesOtherVariables.
func (s *EnvironmentVariableUpdate) GetUsesOtherVariables() OptBool {
	return s.UsesOtherVariables
}

// SetName sets the value of Name.
func (s *EnvironmentVariableUpdate) SetName(val string) {
	s.Name = val
}

// SetValue sets the value of Value.
func (s *EnvironmentVariableUpdate) SetValue(val string) {
	s.Value = val
}

// SetUsesOtherVariables sets the value of UsesOtherVariables.
func (s *EnvironmentVariableUpdate) SetUsesOtherVariables(val OptBool) {
	s.UsesOtherVariables = val
}

type Error struct {
	// Сообщение об ошибке.
	Error OptString `json:"error"`
}

// GetError returns the value of Error.
func (s *Error) GetError() OptString {
	return s.Error
}

// SetError sets the value of Error.
func (s *Error) SetError(val OptString) {
	s.Error = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

type GetGlobalEnvVarsOK struct {
	EnvVars OptNilEnvironmentVariableArray `json:"env_vars"`
}

// GetEnvVars returns the value of EnvVars.
func (s *GetGlobalEnvVarsOK) GetEnvVars() OptNilEnvironmentVariableArray {
	return s.EnvVars
}

// SetEnvVars sets the value of EnvVars.
func (s *GetGlobalEnvVarsOK) SetEnvVars(val OptNilEnvironmentVariableArray) {
	s.EnvVars = val
}

type GetProjectRunsOK struct {
	Runs OptNilProjectRunArray `json:"runs"`
}

// GetRuns returns the value of Runs.
func (s *GetProjectRunsOK) GetRuns() OptNilProjectRunArray {
	return s.Runs
}

// SetRuns sets the value of Runs.
func (s *GetProjectRunsOK) SetRuns(val OptNilProjectRunArray) {
	s.Runs = val
}

type GetProjectsOK struct {
	Projects OptNilProjectListItemArray `json:"projects"`
}

// GetProjects returns the value of Projects.
func (s *GetProjectsOK) GetProjects() OptNilProjectListItemArray {
	return s.Projects
}

// SetProjects sets the value of Projects.
func (s *GetProjectsOK) SetProjects(val OptNilProjectListItemArray) {
	s.Projects = val
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilDateTime returns new OptNilDateTime with value set to v.
func NewOptNilDateTime(v time.Time) OptNilDateTime {
	return OptNilDateTime{
		Value: v,
		Set:   true,
	}
}

// OptNilDateTime is optional nullable time.Time.
type OptNilDateTime struct {
	Value time.Time
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilDateTime was set.
func (o OptNilDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilDateTime) SetToNull() {
	o.Set = true
	o.Null = true
	var v time.Time
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilEnvironmentVariableArray returns new OptNilEnvironmentVariableArray with value set to v.
func NewOptNilEnvironmentVariableArray(v []EnvironmentVariable) OptNilEnvironmentVariableArray {
	return OptNilEnvironmentVariableArray{
		Value: v,
		Set:   true,
	}
}

// OptNilEnvironmentVariableArray is optional nullable []EnvironmentVariable.
type OptNilEnvironmentVariableArray struct {
	Value []EnvironmentVariable
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilEnvironmentVariableArray was set.
func (o OptNilEnvironmentVariableArray) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilEnvironmentVariableArray) Reset() {
	var v []EnvironmentVariable
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilEnvironmentVariableArray) SetTo(v []EnvironmentVariable) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilEnvironmentVariableArray) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilEnvironmentVariableArray) SetToNull() {
	o.Set = true
	o.Null = true
	var v []EnvironmentVariable
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilEnvironmentVariableArray) Get() (v []EnvironmentVariable, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilEnvironmentVariableArray) Or(d []EnvironmentVariable) []EnvironmentVariable {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilProjectEnvironmentVariableArray returns new OptNilProjectEnvironmentVariableArray with value set to v.
func NewOptNilProjectEnvironmentVariableArray(v []ProjectEnvironmentVariable) OptNilProjectEnvironmentVariableArray {
	return OptNilProjectEnvironmentVariableArray{
		Value: v,
		Set:   true,
	}
}

// OptNilProjectEnvironmentVariableArray is optional nullable []ProjectEnvironmentVariable.
type OptNilProjectEnvironmentVariableArray struct {
	Value []ProjectEnvironmentVariable
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilProjectEnvironmentVariableArray was set.
func (o OptNilProjectEnvironmentVariableArray) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilProjectEnvironmentVariableArray) Reset() {
	var v []ProjectEnvironmentVariable
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilProjectEnvironmentVariableArray) SetTo(v []ProjectEnvironmentVariable) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilProjectEnvironmentVariableArray) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilProjectEnvironmentVariableArray) SetToNull() {
	o.Set = true
	o.Null = true
	var v []ProjectEnvironmentVariable
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilProjectEnvironmentVariableArray) Get() (v []ProjectEnvironmentVariable, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilProjectEnvironmentVariableArray) Or(d []ProjectEnvironmentVariable) []ProjectEnvironmentVariable {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilProjectListItemArray returns new OptNilProjectListItemArray with value set to v.
func NewOptNilProjectListItemArray(v []ProjectListItem) OptNilProjectListItemArray {
	return OptNilProjectListItemArray{
		Value: v,
		Set:   true,
	}
}

// OptNilProjectListItemArray is optional nullable []ProjectListItem.
type OptNilProjectListItemArray struct {
	Value []ProjectListItem
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilProjectListItemArray was set.
func (o OptNilProjectListItemArray) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilProjectListItemArray) Reset() {
	var v []ProjectListItem
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilProjectListItemArray) SetTo(v []ProjectListItem) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilProjectListItemArray) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilProjectListItemArray) SetToNull() {
	o.Set = true
	o.Null = true
	var v []ProjectListItem
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilProjectListItemArray) Get() (v []ProjectListItem, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilProjectListItemArray) Or(d []ProjectListItem) []ProjectListItem {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilProjectRunArray returns new OptNilProjectRunArray with value set to v.
func NewOptNilProjectRunArray(v []ProjectRun) OptNilProjectRunArray {
	return OptNilProjectRunArray{
		Value: v,
		Set:   true,
	}
}

// OptNilProjectRunArray is optional nullable []ProjectRun.
type OptNilProjectRunArray struct {
	Value []ProjectRun
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilProjectRunArray was set.
func (o OptNilProjectRunArray) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilProjectRunArray) Reset() {
	var v []ProjectRun
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilProjectRunArray) SetTo(v []ProjectRun) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilProjectRunArray) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilProjectRunArray) SetToNull() {
	o.Set = true
	o.Null = true
	var v []ProjectRun
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilProjectRunArray) Get() (v []ProjectRun, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilProjectRunArray) Or(d []ProjectRun) []ProjectRun {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilProjectRunGitCommitArray returns new OptNilProjectRunGitCommitArray with value set to v.
func NewOptNilProjectRunGitCommitArray(v []ProjectRunGitCommit) OptNilProjectRunGitCommitArray {
	return OptNilProjectRunGitCommitArray{
		Value: v,
		Set:   true,
	}
}

// OptNilProjectRunGitCommitArray is optional nullable []ProjectRunGitCommit.
type OptNilProjectRunGitCommitArray struct {
	Value []ProjectRunGitCommit
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilProjectRunGitCommitArray was set.
func (o OptNilProjectRunGitCommitArray) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilProjectRunGitCommitArray) Reset() {
	var v []ProjectRunGitCommit
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilProjectRunGitCommitArray) SetTo(v []ProjectRunGitCommit) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilProjectRunGitCommitArray) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilProjectRunGitCommitArray) SetToNull() {
	o.Set = true
	o.Null = true
	var v []ProjectRunGitCommit
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilProjectRunGitCommitArray) Get() (v []ProjectRunGitCommit, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilProjectRunGitCommitArray) Or(d []ProjectRunGitCommit) []ProjectRunGitCommit {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilProjectRunStageArray returns new OptNilProjectRunStageArray with value set to v.
func NewOptNilProjectRunStageArray(v []ProjectRunStage) OptNilProjectRunStageArray {
	return OptNilProjectRunStageArray{
		Value: v,
		Set:   true,
	}
}

// OptNilProjectRunStageArray is optional nullable []ProjectRunStage.
type OptNilProjectRunStageArray struct {
	Value []ProjectRunStage
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilProjectRunStageArray was set.
func (o OptNilProjectRunStageArray) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilProjectRunStageArray) Reset() {
	var v []ProjectRunStage
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilProjectRunStageArray) SetTo(v []ProjectRunStage) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilProjectRunStageArray) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilProjectRunStageArray) SetToNull() {
	o.Set = true
	o.Null = true
	var v []ProjectRunStage
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilProjectRunStageArray) Get() (v []ProjectRunStage, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilProjectRunStageArray) Or(d []ProjectRunStage) []ProjectRunStage {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilUint returns new OptNilUint with value set to v.
func NewOptNilUint(v uint) OptNilUint {
	return OptNilUint{
		Value: v,
		Set:   true,
	}
}

// OptNilUint is optional nullable uint.
type OptNilUint struct {
	Value uint
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilUint was set.
func (o OptNilUint) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilUint) Reset() {
	var v uint
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilUint) SetTo(v uint) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilUint) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilUint) SetToNull() {
	o.Set = true
	o.Null = true
	var v uint
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilUint) Get() (v uint, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilUint) Or(d uint) uint {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptProjectLastRun returns new OptProjectLastRun with value set to v.
func NewOptProjectLastRun(v ProjectLastRun) OptProjectLastRun {
	return OptProjectLastRun{
		Value: v,
		Set:   true,
	}
}

// OptProjectLastRun is optional ProjectLastRun.
type OptProjectLastRun struct {
	Value ProjectLastRun
	Set   bool
}

// IsSet returns true if OptProjectLastRun was set.
func (o OptProjectLastRun) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptProjectLastRun) Reset() {
	var v ProjectLastRun
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptProjectLastRun) SetTo(v ProjectLastRun) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptProjectLastRun) Get() (v ProjectLastRun, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptProjectLastRun) Or(d ProjectLastRun) ProjectLastRun {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUint returns new OptUint with value set to v.
func NewOptUint(v uint) OptUint {
	return OptUint{
		Value: v,
		Set:   true,
	}
}

// OptUint is optional uint.
type OptUint struct {
	Value uint
	Set   bool
}

// IsSet returns true if OptUint was set.
func (o OptUint) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUint) Reset() {
	var v uint
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUint) SetTo(v uint) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUint) Get() (v uint, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUint) Or(d uint) uint {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Проект — конфигурация автоматизированного
// пайплайна для репозитория.
// Ref: #/components/schemas/Project
type Project struct {
	// Уникальный идентификатор проекта.
	ID OptUint `json:"id"`
	// Дата и время создания проекта.
	CreatedAt OptDateTime `json:"created_at"`
	// Дата и время последнего изменения конфигурации.
	UpdatedAt OptDateTime `json:"updated_at"`
	// Флаг включения автоматического расписания (cron).
	CronEnabled OptBool `json:"cron_enabled"`
	// Cron-выражение для автоматического запуска.
	CronSchedule OptString `json:"cron_schedule"`
	// Человеко-читаемое имя проекта.
	Name string `json:"name"`
	// Локальный путь к рабочей директории проекта.
	Dir OptString `json:"dir"`
	// URL Git-репозитория.
	GitURL OptString `json:"git_url"`
	// Имя ветки Git для сборки.
	GitBranch OptString `json:"git_branch"`
	// Флаг перезапуска приложения после выполнения задачи.
	RestartAfter OptBool `json:"restart_after"`
	// Количество последних запусков для хранения (0 -
	// отключить).
	RetentionCount OptInt32 `json:"retention_count"`
	// Флаг использования переменных окружения root
	// пользователя.
	WithRootEnv OptBool `json:"with_root_env"`
	// Этапы пайплайна (выполняются последовательно).
	Stages []ProjectStage `json:"stages"`
	// Переменные окружения проекта.
	EnvVars OptNilProjectEnvironmentVariableArray `json:"env_vars"`
}

// GetID returns the value of ID.
func (s *Project) GetID() OptUint {
	return s.ID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Project) GetCreatedAt() OptDateTime {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Project) GetUpdatedAt() OptDateTime {
	return s.UpdatedAt
}

// GetCronEnabled returns the value of CronEnabled.
func (s *Project) GetCronEnabled() OptBool {
	return s.CronEnabled
}

// GetCronSchedule returns the value of CronSchedule.
func (s *Project) GetCronSchedule() OptString {
	return s.CronSchedule
}

// GetName returns the value of Name.
func (s *Project) GetName() string {
	return s.Name
}

// GetDir returns the value of Dir.
func (s *Project) GetDir() OptString {
	return s.Dir
}

// GetGitURL returns the value of GitURL.
func (s *Project) GetGitURL() OptString {
	return s.GitURL
}

// GetGitBranch returns the value of GitBranch.
func (s *Project) GetGitBranch() OptString {
	return s.GitBranch
}

// GetRestartAfter returns the value of RestartAfter.
func (s *Project) GetRestartAfter() OptBool {
	return s.RestartAfter
}

// GetRetentionCount returns the value of RetentionCount.
func (s *Project) GetRetentionCount() OptInt32 {
	return s.RetentionCount
}

// GetWithRootEnv returns the value of WithRootEnv.
func (s *Project) GetWithRootEnv() OptBool {
	return s.WithRootEnv
}

// GetStages returns the value of Stages.
func (s *Project) GetStages() []ProjectStage {
	return s.Stages
}

// GetEnvVars returns the value of EnvVars.
func (s *Project) GetEnvVars() OptNilProjectEnvironmentVariableArray {
	return s.EnvVars
}

// SetID sets the value of ID.
func (s *Project) SetID(val OptUint) {
	s.ID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Project) SetCreatedAt(val OptDateTime) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Project) SetUpdatedAt(val OptDateTime) {
	s.UpdatedAt = val
}

// SetCronEnabled sets the value of CronEnabled.
func (s *Project) SetCronEnabled(val OptBool) {
	s.CronEnabled = val
}

// SetCronSchedule sets the value of CronSchedule.
func (s *Project) SetCronSchedule(val OptString) {
	s.CronSchedule = val
}

// SetName sets the value of Name.
func (s *Project) SetName(val string) {
	s.Name = val
}

// SetDir sets the value of Dir.
func (s *Project) SetDir(val OptString) {
	s.Dir = val
}

// SetGitURL sets the value of GitURL.
func (s *Project) SetGitURL(val OptString) {
	s.GitURL = val
}

// SetGitBranch sets the value of GitBranch.
func (s *Project) SetGitBranch(val OptString) {
	s.GitBranch = val
}

// SetRestartAfter sets the value of RestartAfter.
func (s *Project) SetRestartAfter(val OptBool) {
	s.RestartAfter = val
}

// SetRetentionCount sets the value of RetentionCount.
func (s *Project) SetRetentionCount(val OptInt32) {
	s.RetentionCount = val
}

// SetWithRootEnv sets the value of WithRootEnv.
func (s *Project) SetWithRootEnv(val OptBool) {
	s.WithRootEnv = val
}

// SetStages sets the value of Stages.
func (s *Project) SetStages(val []ProjectStage) {
	s.Stages = val
}

// SetEnvVars sets the value of EnvVars.
func (s *Project) SetEnvVars(val OptNilProjectEnvironmentVariableArray) {
	s.EnvVars = val
}

// Данные для создания нового проекта.
// Ref: #/components/schemas/ProjectCreate
type ProjectCreate struct {
	// Флаг включения автоматического расписания (cron).
	CronEnabled OptBool `json:"cron_enabled"`
	// Cron-выражение для автоматического запуска.
	CronSchedule OptString `json:"cron_schedule"`
	// Человеко-читаемое имя проекта.
	Name string `json:"name"`
	// Локальный путь к рабочей директории проекта.
	Dir OptString `json:"dir"`
	// URL Git-репозитория.
	GitURL OptString `json:"git_url"`
	// Имя ветки Git для сборки.
	GitBranch OptString `json:"git_branch"`
	// Флаг перезапуска приложения после выполнения задачи.
	RestartAfter OptBool `json:"restart_after"`
	// Количество последних запусков для хранения.
	RetentionCount OptInt32 `json:"retention_count"`
	// Флаг использования переменных окружения root
	// пользователя.
	WithRootEnv OptBool `json:"with_root_env"`
	// Этапы пайплайна (выполняются последовательно).
	Stages []ProjectStage `json:"stages"`
	// Переменные окружения проекта.
	EnvVars OptNilProjectEnvironmentVariableArray `json:"env_vars"`
}

// GetCronEnabled returns the value of CronEnabled.
func (s *ProjectCreate) GetCronEnabled() OptBool {
	return s.CronEnabled
}

// GetCronSchedule returns the value of CronSchedule.
func (s *ProjectCreate) GetCronSchedule() OptString {
	return s.CronSchedule
}

// GetName returns the value of Name.
func (s *ProjectCreate) GetName() string {
	return s.Name
}

// GetDir returns the value of Dir.
func (s *ProjectCreate) GetDir() OptString {
	return s.Dir
}

// GetGitURL returns the value of GitURL.
func (s *ProjectCreate) GetGitURL() OptString {
	return s.GitURL
}

// GetGitBranch returns the value of GitBranch.
func (s *ProjectCreate) GetGitBranch() OptString {
	return s.GitBranch
}

// GetRestartAfter returns the value of RestartAfter.
func (s *ProjectCreate) GetRestartAfter() OptBool {
	return s.RestartAfter
}

// GetRetentionCount returns the value of RetentionCount.
func (s *ProjectCreate) GetRetentionCount() OptInt32 {
	return s.RetentionCount
}

// GetWithRootEnv returns the value of WithRootEnv.
func (s *ProjectCreate) GetWithRootEnv() OptBool {
	return s.WithRootEnv
}

// GetStages returns the value of Stages.
func (s *ProjectCreate) GetStages() []ProjectStage {
	return s.Stages
}

// GetEnvVars returns the value of EnvVars.
func (s *ProjectCreate) GetEnvVars() OptNilProjectEnvironmentVariableArray {
	return s.EnvVars
}

// SetCronEnabled sets the value of CronEnabled.
func (s *ProjectCreate) SetCronEnabled(val OptBool) {
	s.CronEnabled = val
}

// SetCronSchedule sets the value of CronSchedule.
func (s *ProjectCreate) SetCronSchedule(val OptString) {
	s.CronSchedule = val
}

// SetName sets the value of Name.
func (s *ProjectCreate) SetName(val string) {
	s.Name = val
}

// SetDir sets the value of Dir.
func (s *ProjectCreate) SetDir(val OptString) {
	s.Dir = val
}

// SetGitURL sets the value of GitURL.
func (s *ProjectCreate) SetGitURL(val OptString) {
	s.GitURL = val
}

// SetGitBranch sets the value of GitBranch.
func (s *ProjectCreate) SetGitBranch(val OptString) {
	s.GitBranch = val
}

// SetRestartAfter sets the value of RestartAfter.
func (s *ProjectCreate) SetRestartAfter(val OptBool) {
	s.RestartAfter = val
}

// SetRetentionCount sets the value of RetentionCount.
func (s *ProjectCreate) SetRetentionCount(val OptInt32) {
	s.RetentionCount = val
}

// SetWithRootEnv sets the value of WithRootEnv.
func (s *ProjectCreate) SetWithRootEnv(val OptBool) {
	s.WithRootEnv = val
}

// SetStages sets the value of Stages.
func (s *ProjectCreate) SetStages(val []ProjectStage) {
	s.Stages = val
}

// SetEnvVars sets the value of EnvVars.
func (s *ProjectCreate) SetEnvVars(val OptNilProjectEnvironmentVariableArray) {
	s.EnvVars = val
}

// Переменная окружения проекта — именованная пара
// «ключ-значение» для передачи конфигурации в скрипты
// пайплайна.
// Ref: #/components/schemas/ProjectEnvironmentVariable
type ProjectEnvironmentVariable struct {
	// Уникальный идентификатор переменной.
	ID OptUint `json:"id"`
	// Имя переменной окружения (например, DATABASE_URL, API_KEY).
	Name string `json:"name"`
	// Значение переменной окружения.
	Value string `json:"value"`
	// Флаг использования других переменных (формат ${VAR_NAME}).
	UsesOtherVariables OptBool `json:"uses_other_variables"`
}

// GetID returns the value of ID.
func (s *ProjectEnvironmentVariable) GetID() OptUint {
	return s.ID
}

// GetName returns the value of Name.
func (s *ProjectEnvironmentVariable) GetName() string {
	return s.Name
}

// GetValue returns the value of Value.
func (s *ProjectEnvironmentVariable) GetValue() string {
	return s.Value
}

// GetUsesOtherVariables returns the value of UsesOtherVariables.
func (s *ProjectEnvironmentVariable) GetUsesOtherVariables() OptBool {
	return s.UsesOtherVariables
}

// SetID sets the value of ID.
func (s *ProjectEnvironmentVariable) SetID(val OptUint) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *ProjectEnvironmentVariable) SetName(val string) {
	s.Name = val
}

// SetValue sets the value of Value.
func (s *ProjectEnvironmentVariable) SetValue(val string) {
	s.Value = val
}

// SetUsesOtherVariables sets the value of UsesOtherVariables.
func (s *ProjectEnvironmentVariable) SetUsesOtherVariables(val OptBool) {
	s.UsesOtherVariables = val
}

// Информация о последнем запуске проекта.
// Ref: #/components/schemas/ProjectLastRun
type ProjectLastRun struct {
	// Время начала запуска.
	CreatedAt OptDateTime `json:"created_at"`
	// Флаг успешного завершения всех этапов.
	Success OptBool `json:"success"`
	// Флаг ожидания начала выполнения.
	Pending OptBool `json:"pending"`
	// Флаг активного выполнения.
	Processing OptBool `json:"processing"`
	// Время выполнения последнего запуска (в миллисекундах).
	Duration OptInt64 `json:"duration"`
}

// GetCreatedAt returns the value of CreatedAt.
func (s *ProjectLastRun) GetCreatedAt() OptDateTime {
	return s.CreatedAt
}

// GetSuccess returns the value of Success.
func (s *ProjectLastRun) GetSuccess() OptBool {
	return s.Success
}

// GetPending returns the value of Pending.
func (s *ProjectLastRun) GetPending() OptBool {
	return s.Pending
}

// GetProcessing returns the value of Processing.
func (s *ProjectLastRun) GetProcessing() OptBool {
	return s.Processing
}

// GetDuration returns the value of Duration.
func (s *ProjectLastRun) GetDuration() OptInt64 {
	return s.Duration
}

// SetCreatedAt sets the value of CreatedAt.
func (s *ProjectLastRun) SetCreatedAt(val OptDateTime) {
	s.CreatedAt = val
}

// SetSuccess sets the value of Success.
func (s *ProjectLastRun) SetSuccess(val OptBool) {
	s.Success = val
}

// SetPending sets the value of Pending.
func (s *ProjectLastRun) SetPending(val OptBool) {
	s.Pending = val
}

// SetProcessing sets the value of Processing.
func (s *ProjectLastRun) SetProcessing(val OptBool) {
	s.Processing = val
}

// SetDuration sets the value of Duration.
func (s *ProjectLastRun) SetDuration(val OptInt64) {
	s.Duration = val
}

// Элемент списка проектов — краткая информация о
// проекте.
// Ref: #/components/schemas/ProjectListItem
type ProjectListItem struct {
	// Уникальный идентификатор проекта.
	ID uint `json:"id"`
	// Человеко-читаемое имя проекта.
	Name string `json:"name"`
	// Флаг включения автоматического расписания (cron).
	CronEnabled OptBool `json:"cron_enabled"`
	// Время последнего успешного запуска.
	LastSuccessfulRunAt OptNilDateTime    `json:"last_successful_run_at"`
	LastRun             OptProjectLastRun `json:"last_run"`
}

// GetID returns the value of ID.
func (s *ProjectListItem) GetID() uint {
	return s.ID
}

// GetName returns the value of Name.
func (s *ProjectListItem) GetName() string {
	return s.Name
}

// GetCronEnabled returns the value of CronEnabled.
func (s *ProjectListItem) GetCronEnabled() OptBool {
	return s.CronEnabled
}

// GetLastSuccessfulRunAt returns the value of LastSuccessfulRunAt.
func (s *ProjectListItem) GetLastSuccessfulRunAt() OptNilDateTime {
	return s.LastSuccessfulRunAt
}

// GetLastRun returns the value of LastRun.
func (s *ProjectListItem) GetLastRun() OptProjectLastRun {
	return s.LastRun
}

// SetID sets the value of ID.
func (s *ProjectListItem) SetID(val uint) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *ProjectListItem) SetName(val string) {
	s.Name = val
}

// SetCronEnabled sets the value of CronEnabled.
func (s *ProjectListItem) SetCronEnabled(val OptBool) {
	s.CronEnabled = val
}

// SetLastSuccessfulRunAt sets the value of LastSuccessfulRunAt.
func (s *ProjectListItem) SetLastSuccessfulRunAt(val OptNilDateTime) {
	s.LastSuccessfulRunAt = val
}

// SetLastRun sets the value of LastRun.
func (s *ProjectListItem) SetLastRun(val OptProjectLastRun) {
	s.LastRun = val
}

// Запуск проекта — результат выполнения пайплайна.
// Ref: #/components/schemas/ProjectRun
type ProjectRun struct {
	// Уникальный идентификатор запуска.
	ID OptUint `json:"id"`
	// Время начала запуска.
	CreatedAt OptDateTime `json:"created_at"`
	// Время последнего обновления статуса.
	UpdatedAt OptDateTime `json:"updated_at"`
	// Ссылка на проект.
	ProjectID OptUint `json:"project_id"`
	// Флаг успешного завершения всех этапов.
	Success OptBool `json:"success"`
	// Флаг ожидания начала выполнения.
	Pending OptBool `json:"pending"`
	// Флаг активного выполнения.
	Processing OptBool `json:"processing"`
	// Время выполнения запуска (в миллисекундах).
	Duration OptInt64 `json:"duration"`
	// Лог ошибки, если запуск завершился неудачей.
	FailLog OptString `json:"fail_log"`
	// Результаты выполнения этапов.
	Stages OptNilProjectRunStageArray `json:"stages"`
	// Git-коммиты, связанные с запуском.
	GitCommits OptNilProjectRunGitCommitArray `json:"git_commits"`
}

// GetID returns the value of ID.
func (s *ProjectRun) GetID() OptUint {
	return s.ID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *ProjectRun) GetCreatedAt() OptDateTime {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *ProjectRun) GetUpdatedAt() OptDateTime {
	return s.UpdatedAt
}

// GetProjectID returns the value of ProjectID.
func (s *ProjectRun) GetProjectID() OptUint {
	return s.ProjectID
}

// GetSuccess returns the value of Success.
func (s *ProjectRun) GetSuccess() OptBool {
	return s.Success
}

// GetPending returns the value of Pending.
func (s *ProjectRun) GetPending() OptBool {
	return s.Pending
}

// GetProcessing returns the value of Processing.
func (s *ProjectRun) GetProcessing() OptBool {
	return s.Processing
}

// GetDuration returns the value of Duration.
func (s *ProjectRun) GetDuration() OptInt64 {
	return s.Duration
}

// GetFailLog returns the value of FailLog.
func (s *ProjectRun) GetFailLog() OptString {
	return s.FailLog
}

// GetStages returns the value of Stages.
func (s *ProjectRun) GetStages() OptNilProjectRunStageArray {
	return s.Stages
}

// GetGitCommits returns the value of GitCommits.
func (s *ProjectRun) GetGitCommits() OptNilProjectRunGitCommitArray {
	return s.GitCommits
}

// SetID sets the value of ID.
func (s *ProjectRun) SetID(val OptUint) {
	s.ID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *ProjectRun) SetCreatedAt(val OptDateTime) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *ProjectRun) SetUpdatedAt(val OptDateTime) {
	s.UpdatedAt = val
}

// SetProjectID sets the value of ProjectID.
func (s *ProjectRun) SetProjectID(val OptUint) {
	s.ProjectID = val
}

// SetSuccess sets the value of Success.
func (s *ProjectRun) SetSuccess(val OptBool) {
	s.Success = val
}

// SetPending sets the value of Pending.
func (s *ProjectRun) SetPending(val OptBool) {
	s.Pending = val
}

// SetProcessing sets the value of Processing.
func (s *ProjectRun) SetProcessing(val OptBool) {
	s.Processing = val
}

// SetDuration sets the value of Duration.
func (s *ProjectRun) SetDuration(val OptInt64) {
	s.Duration = val
}

// SetFailLog sets the value of FailLog.
func (s *ProjectRun) SetFailLog(val OptString) {
	s.FailLog = val
}

// SetStages sets the value of Stages.
func (s *ProjectRun) SetStages(val OptNilProjectRunStageArray) {
	s.Stages = val
}

// SetGitCommits sets the value of GitCommits.
func (s *ProjectRun) SetGitCommits(val OptNilProjectRunGitCommitArray) {
	s.GitCommits = val
}

// Git-коммит, связанный с запуском.
// Ref: #/components/schemas/ProjectRunGitCommit
type ProjectRunGitCommit struct {
	// Порядковый номер коммита.
	Number OptInt32 `json:"number"`
	// Хэш коммита в Git.
	Hash OptString `json:"hash"`
	// Сообщение коммита (первая строка).
	Subject OptString `json:"subject"`
}

// GetNumber returns the value of Number.
func (s *ProjectRunGitCommit) GetNumber() OptInt32 {
	return s.Number
}

// GetHash returns the value of Hash.
func (s *ProjectRunGitCommit) GetHash() OptString {
	return s.Hash
}

// GetSubject returns the value of Subject.
func (s *ProjectRunGitCommit) GetSubject() OptString {
	return s.Subject
}

// SetNumber sets the value of Number.
func (s *ProjectRunGitCommit) SetNumber(val OptInt32) {
	s.Number = val
}

// SetHash sets the value of Hash.
func (s *ProjectRunGitCommit) SetHash(val OptString) {
	s.Hash = val
}

// SetSubject sets the value of Subject.
func (s *ProjectRunGitCommit) SetSubject(val OptString) {
	s.Subject = val
}

// Результат выполнения конкретного этапа запуска.
// Ref: #/components/schemas/ProjectRunStage
type ProjectRunStage struct {
	// Номер этапа.
	StageNumber OptInt32 `json:"stage_number"`
	// Флаг успешного выполнения этапа.
	Success OptBool `json:"success"`
	// Время выполнения этапа (в миллисекундах).
	Duration OptInt64 `json:"duration"`
	// Лог выполнения этапа.
	Log OptString `json:"log"`
}

// GetStageNumber returns the value of StageNumber.
func (s *ProjectRunStage) GetStageNumber() OptInt32 {
	return s.StageNumber
}

// GetSuccess returns the value of Success.
func (s *ProjectRunStage) GetSuccess() OptBool {
	return s.Success
}

// GetDuration returns the value of Duration.
func (s *ProjectRunStage) GetDuration() OptInt64 {
	return s.Duration
}

// GetLog returns the value of Log.
func (s *ProjectRunStage) GetLog() OptString {
	return s.Log
}

// SetStageNumber sets the value of StageNumber.
func (s *ProjectRunStage) SetStageNumber(val OptInt32) {
	s.StageNumber = val
}

// SetSuccess sets the value of Success.
func (s *ProjectRunStage) SetSuccess(val OptBool) {
	s.Success = val
}

// SetDuration sets the value of Duration.
func (s *ProjectRunStage) SetDuration(val OptInt64) {
	s.Duration = val
}

// SetLog sets the value of Log.
func (s *ProjectRunStage) SetLog(val OptString) {
	s.Log = val
}

// Этап проекта — один шаг в пайплайне выполнения.
// Ref: #/components/schemas/ProjectStage
type ProjectStage struct {
	// Порядковый номер этапа (начинается с 1).
	Number int32 `json:"number"`
	// Команда или скрипт для выполнения.
	Script string `json:"script"`
}

// GetNumber returns the value of Number.
func (s *ProjectStage) GetNumber() int32 {
	return s.Number
}

// GetScript returns the value of Script.
func (s *ProjectStage) GetScript() string {
	return s.Script
}

// SetNumber sets the value of Number.
func (s *ProjectStage) SetNumber(val int32) {
	s.Number = val
}

// SetScript sets the value of Script.
func (s *ProjectStage) SetScript(val string) {
	s.Script = val
}

// Данные для обновления проекта.
// Ref: #/components/schemas/ProjectUpdate
type ProjectUpdate struct {
	// Уникальный идентификатор проекта.
	ID uint `json:"id"`
	// Флаг включения автоматического расписания (cron).
	CronEnabled OptBool `json:"cron_enabled"`
	// Cron-выражение для автоматического запуска.
	CronSchedule OptString `json:"cron_schedule"`
	// Человеко-читаемое имя проекта.
	Name string `json:"name"`
	// Локальный путь к рабочей директории проекта.
	Dir OptString `json:"dir"`
	// URL Git-репозитория.
	GitURL OptString `json:"git_url"`
	// Имя ветки Git для сборки.
	GitBranch OptString `json:"git_branch"`
	// Флаг перезапуска приложения после выполнения задачи.
	RestartAfter OptBool `json:"restart_after"`
	// Количество последних запусков для хранения.
	RetentionCount OptInt32 `json:"retention_count"`
	// Флаг использования переменных окружения root
	// пользователя.
	WithRootEnv OptBool `json:"with_root_env"`
	// Этапы пайплайна (выполняются последовательно).
	Stages []ProjectStage `json:"stages"`
	// Переменные окружения проекта.
	EnvVars OptNilProjectEnvironmentVariableArray `json:"env_vars"`
}

// GetID returns the value of ID.
func (s *ProjectUpdate) GetID() uint {
	return s.ID
}

// GetCronEnabled returns the value of CronEnabled.
func (s *ProjectUpdate) GetCronEnabled() OptBool {
	return s.CronEnabled
}

// GetCronSchedule returns the value of CronSchedule.
func (s *ProjectUpdate) GetCronSchedule() OptString {
	return s.CronSchedule
}

// GetName returns the value of Name.
func (s *ProjectUpdate) GetName() string {
	return s.Name
}

// GetDir returns the value of Dir.
func (s *ProjectUpdate) GetDir() OptString {
	return s.Dir
}

// GetGitURL returns the value of GitURL.
func (s *ProjectUpdate) GetGitURL() OptString {
	return s.GitURL
}

// GetGitBranch returns the value of GitBranch.
func (s *ProjectUpdate) GetGitBranch() OptString {
	return s.GitBranch
}

// GetRestartAfter returns the value of RestartAfter.
func (s *ProjectUpdate) GetRestartAfter() OptBool {
	return s.RestartAfter
}

// GetRetentionCount returns the value of RetentionCount.
func (s *ProjectUpdate) GetRetentionCount() OptInt32 {
	return s.RetentionCount
}

// GetWithRootEnv returns the value of WithRootEnv.
func (s *ProjectUpdate) GetWithRootEnv() OptBool {
	return s.WithRootEnv
}

// GetStages returns the value of Stages.
func (s *ProjectUpdate) GetStages() []ProjectStage {
	return s.Stages
}

// GetEnvVars returns the value of EnvVars.
func (s *ProjectUpdate) GetEnvVars() OptNilProjectEnvironmentVariableArray {
	return s.EnvVars
}

// SetID sets the value of ID.
func (s *ProjectUpdate) SetID(val uint) {
	s.ID = val
}

// SetCronEnabled sets the value of CronEnabled.
func (s *ProjectUpdate) SetCronEnabled(val OptBool) {
	s.CronEnabled = val
}

// SetCronSchedule sets the value of CronSchedule.
func (s *ProjectUpdate) SetCronSchedule(val OptString) {
	s.CronSchedule = val
}

// SetName sets the value of Name.
func (s *ProjectUpdate) SetName(val string) {
	s.Name = val
}

// SetDir sets the value of Dir.
func (s *ProjectUpdate) SetDir(val OptString) {
	s.Dir = val
}

// SetGitURL sets the value of GitURL.
func (s *ProjectUpdate) SetGitURL(val OptString) {
	s.GitURL = val
}

// SetGitBranch sets the value of GitBranch.
func (s *ProjectUpdate) SetGitBranch(val OptString) {
	s.GitBranch = val
}

// SetRestartAfter sets the value of RestartAfter.
func (s *ProjectUpdate) SetRestartAfter(val OptBool) {
	s.RestartAfter = val
}

// SetRetentionCount sets the value of RetentionCount.
func (s *ProjectUpdate) SetRetentionCount(val OptInt32) {
	s.RetentionCount = val
}

// SetWithRootEnv sets the value of WithRootEnv.
func (s *ProjectUpdate) SetWithRootEnv(val OptBool) {
	s.WithRootEnv = val
}

// SetStages sets the value of Stages.
func (s *ProjectUpdate) SetStages(val []ProjectStage) {
	s.Stages = val
}

// SetEnvVars sets the value of EnvVars.
func (s *ProjectUpdate) SetEnvVars(val OptNilProjectEnvironmentVariableArray) {
	s.EnvVars = val
}

// UpdateGlobalEnvVarNoContent is response for UpdateGlobalEnvVar operation.
type UpdateGlobalEnvVarNoContent struct{}

// UpdateProjectNoContent is response for UpdateProject operation.
type UpdateProjectNoContent struct{}
