// Code generated by ogen, DO NOT EDIT.

package ogenapi

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateGlobalEnvVarOperation OperationName = "CreateGlobalEnvVar"
	CreateProjectOperation      OperationName = "CreateProject"
	CreateProjectRunOperation   OperationName = "CreateProjectRun"
	DeleteGlobalEnvVarOperation OperationName = "DeleteGlobalEnvVar"
	DeleteProjectOperation      OperationName = "DeleteProject"
	GetGlobalEnvVarOperation    OperationName = "GetGlobalEnvVar"
	GetGlobalEnvVarsOperation   OperationName = "GetGlobalEnvVars"
	GetProjectOperation         OperationName = "GetProject"
	GetProjectRunOperation      OperationName = "GetProjectRun"
	GetProjectRunsOperation     OperationName = "GetProjectRuns"
	GetProjectsOperation        OperationName = "GetProjects"
	UpdateGlobalEnvVarOperation OperationName = "UpdateGlobalEnvVar"
	UpdateProjectOperation      OperationName = "UpdateProject"
)
