// Code generated by ogen, DO NOT EDIT.

package ogenapi

// setDefaults set default value of fields.
func (s *EnvironmentVariableCreate) setDefaults() {
	{
		val := bool(false)
		s.UsesOtherVariables.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EnvironmentVariableUpdate) setDefaults() {
	{
		val := bool(false)
		s.UsesOtherVariables.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *Project) setDefaults() {
	{
		val := bool(false)
		s.CronEnabled.SetTo(val)
	}
	{
		val := bool(false)
		s.RestartAfter.SetTo(val)
	}
	{
		val := int32(10)
		s.RetentionCount.SetTo(val)
	}
	{
		val := bool(false)
		s.WithRootEnv.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ProjectCreate) setDefaults() {
	{
		val := bool(false)
		s.CronEnabled.SetTo(val)
	}
	{
		val := bool(false)
		s.RestartAfter.SetTo(val)
	}
	{
		val := int32(10)
		s.RetentionCount.SetTo(val)
	}
	{
		val := bool(false)
		s.WithRootEnv.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ProjectListItem) setDefaults() {
	{
		val := bool(false)
		s.CronEnabled.SetTo(val)
	}
}
