/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * EasyJet API
 * API для системы непрерывной интеграции и доставки EasyJet.

EasyJet — легковесная CI/CD система для домашних серверов и пет-проектов.

## Возможности

- Управление проектами (создание, чтение, обновление)
- Запуск пайплайнов и мониторинг выполнения
- Просмотр истории запусков и логов
- Интеграция с Git

 * OpenAPI spec version: 1.0.0
 */
/**
 * Этап проекта — один шаг в пайплайне выполнения
 */
export interface ProjectStage {
  /**
   * Порядковый номер этапа (начинается с 1)
   * @minimum 1
   */
  number: number;
  /** Команда или скрипт для выполнения */
  script: string;
}

/**
 * Переменная окружения проекта — именованная пара «ключ-значение» для передачи конфигурации в скрипты пайплайна
 */
export interface ProjectEnvironmentVariable {
  /** Уникальный идентификатор переменной */
  readonly id?: number;
  /** Имя переменной окружения (например, DATABASE_URL, API_KEY) */
  name: string;
  /** Значение переменной окружения */
  value: string;
  /** Флаг использования других переменных (формат ${VAR_NAME}) */
  uses_other_variables?: boolean;
}

/**
 * Проект — конфигурация автоматизированного пайплайна для репозитория
 */
export interface Project {
  /** Уникальный идентификатор проекта */
  readonly id?: number;
  /** Дата и время создания проекта */
  readonly created_at?: string;
  /** Дата и время последнего изменения конфигурации */
  readonly updated_at?: string;
  /** Флаг включения автоматического расписания (cron) */
  cron_enabled?: boolean;
  /** Cron-выражение для автоматического запуска */
  cron_schedule?: string;
  /** Человеко-читаемое имя проекта */
  name: string;
  /** Локальный путь к рабочей директории проекта */
  dir?: string;
  /** URL Git-репозитория */
  git_url?: string;
  /** Имя ветки Git для сборки */
  git_branch?: string;
  /** Флаг перезапуска приложения после выполнения задачи */
  restart_after?: boolean;
  /** Количество последних запусков для хранения (0 - отключить) */
  retention_count?: number;
  /** Флаг использования переменных окружения root пользователя */
  with_root_env?: boolean;
  /** Флаг шаблонного проекта (шаблон не может быть запущен) */
  is_template?: boolean;
  /**
   * Этапы пайплайна (выполняются последовательно)
   * @minItems 1
   * @nullable
   */
  stages: ProjectStage[] | null;
  /**
   * Переменные окружения проекта
   * @nullable
   */
  env_vars?: ProjectEnvironmentVariable[] | null;
}

/**
 * Статус выполнения запуска
 */
export type ProjectLastRunStatus = (typeof ProjectLastRunStatus)[keyof typeof ProjectLastRunStatus];

export const ProjectLastRunStatus = {
  pending: 'pending',
  processing: 'processing',
  success: 'success',
  failed: 'failed',
} as const;

/**
 * Информация о последнем запуске проекта
 */
export interface ProjectLastRun {
  /** Время начала запуска */
  readonly created_at?: string;
  /** Статус выполнения запуска */
  readonly status?: ProjectLastRunStatus;
  /** Время выполнения последнего запуска (в миллисекундах) */
  readonly duration?: number;
}

/**
 * Элемент списка проектов — краткая информация о проекте
 */
export interface ProjectListItem {
  /** Уникальный идентификатор проекта */
  readonly id: number;
  /** Человеко-читаемое имя проекта */
  name: string;
  /** Флаг включения автоматического расписания (cron) */
  cron_enabled?: boolean;
  /** Флаг шаблонного проекта */
  is_template?: boolean;
  /**
   * Время последнего успешного запуска
   * @nullable
   */
  readonly last_successful_run_at?: string | null;
  last_run?: ProjectLastRun;
}

/**
 * Данные для создания нового проекта
 */
export interface ProjectCreate {
  /** Флаг включения автоматического расписания (cron) */
  cron_enabled?: boolean;
  /** Cron-выражение для автоматического запуска */
  cron_schedule?: string;
  /** Человеко-читаемое имя проекта */
  name: string;
  /** Локальный путь к рабочей директории проекта */
  dir?: string;
  /** URL Git-репозитория */
  git_url?: string;
  /** Имя ветки Git для сборки */
  git_branch?: string;
  /** Флаг перезапуска приложения после выполнения задачи */
  restart_after?: boolean;
  /** Количество последних запусков для хранения */
  retention_count?: number;
  /** Флаг использования переменных окружения root пользователя */
  with_root_env?: boolean;
  /** Флаг шаблонного проекта */
  is_template?: boolean;
  /**
   * Этапы пайплайна (выполняются последовательно)
   * @minItems 1
   */
  stages: ProjectStage[];
  /**
   * Переменные окружения проекта
   * @nullable
   */
  env_vars?: ProjectEnvironmentVariable[] | null;
}

/**
 * Данные для обновления проекта
 */
export interface ProjectUpdate {
  /** Уникальный идентификатор проекта */
  id: number;
  /** Флаг включения автоматического расписания (cron) */
  cron_enabled?: boolean;
  /** Cron-выражение для автоматического запуска */
  cron_schedule?: string;
  /** Человеко-читаемое имя проекта */
  name: string;
  /** Локальный путь к рабочей директории проекта */
  dir?: string;
  /** URL Git-репозитория */
  git_url?: string;
  /** Имя ветки Git для сборки */
  git_branch?: string;
  /** Флаг перезапуска приложения после выполнения задачи */
  restart_after?: boolean;
  /** Количество последних запусков для хранения */
  retention_count?: number;
  /** Флаг использования переменных окружения root пользователя */
  with_root_env?: boolean;
  /** Флаг шаблонного проекта */
  is_template?: boolean;
  /**
   * Этапы пайплайна (выполняются последовательно)
   * @minItems 1
   */
  stages: ProjectStage[];
  /**
   * Переменные окружения проекта
   * @nullable
   */
  env_vars?: ProjectEnvironmentVariable[] | null;
}

/**
 * Статус выполнения запуска
 */
export type ProjectRunStatus = (typeof ProjectRunStatus)[keyof typeof ProjectRunStatus];

export const ProjectRunStatus = {
  pending: 'pending',
  processing: 'processing',
  success: 'success',
  failed: 'failed',
} as const;

/**
 * Результат выполнения конкретного этапа запуска
 */
export interface ProjectRunStage {
  /**
   * Номер этапа
   * @minimum 1
   */
  stage_number?: number;
  /** Флаг успешного выполнения этапа */
  readonly success?: boolean;
  /** Время выполнения этапа (в миллисекундах) */
  readonly duration?: number;
  /** Лог выполнения этапа */
  readonly log?: string;
}

/**
 * Git-коммит, связанный с запуском
 */
export interface ProjectRunGitCommit {
  /** Порядковый номер коммита */
  number?: number;
  /** Хэш коммита в Git */
  hash?: string;
  /** Сообщение коммита (первая строка) */
  subject?: string;
}

/**
 * Запуск проекта — результат выполнения пайплайна
 */
export interface ProjectRun {
  /** Уникальный идентификатор запуска */
  readonly id?: number;
  /** Время начала запуска */
  readonly created_at?: string;
  /** Время последнего обновления статуса */
  readonly updated_at?: string;
  /** Ссылка на проект */
  readonly project_id?: number;
  /** Статус выполнения запуска */
  readonly status?: ProjectRunStatus;
  /** Время выполнения запуска (в миллисекундах) */
  readonly duration?: number;
  /** Лог ошибки, если запуск завершился неудачей */
  readonly fail_log?: string;
  /**
   * Результаты выполнения этапов
   * @nullable
   */
  readonly stages?: readonly ProjectRunStage[] | null;
  /**
   * Git-коммиты, связанные с запуском
   * @nullable
   */
  readonly git_commits?: readonly ProjectRunGitCommit[] | null;
}

/**
 * Статус выполнения запуска
 */
export type ProjectRunSummaryStatus =
  (typeof ProjectRunSummaryStatus)[keyof typeof ProjectRunSummaryStatus];

export const ProjectRunSummaryStatus = {
  pending: 'pending',
  processing: 'processing',
  success: 'success',
  failed: 'failed',
} as const;

/**
 * Краткая информация о запуске проекта (для списка запусков, без этапов и коммитов)
 */
export interface ProjectRunSummary {
  /** Уникальный идентификатор запуска */
  readonly id?: number;
  /** Время начала запуска */
  readonly created_at?: string;
  /** Время последнего обновления статуса */
  readonly updated_at?: string;
  /** Ссылка на проект */
  readonly project_id?: number;
  /** Статус выполнения запуска */
  readonly status?: ProjectRunSummaryStatus;
  /** Время выполнения запуска (в миллисекундах) */
  readonly duration?: number;
  /** Лог ошибки, если запуск завершился неудачей */
  readonly fail_log?: string;
}

/**
 * Переменная окружения — именованная пара «ключ-значение» для передачи конфигурации в скрипты пайплайна
 */
export interface EnvironmentVariable {
  /** Уникальный идентификатор переменной */
  readonly id?: number;
  /** Дата и время создания переменной */
  readonly created_at?: string;
  /** Дата и время последнего изменения значения */
  readonly updated_at?: string;
  /**
   * Ссылка на проект (null для глобальных переменных)
   * @nullable
   */
  project_id?: number | null;
  /** Имя переменной окружения (например, DATABASE_URL, API_KEY) */
  name: string;
  /** Значение переменной окружения */
  value: string;
  /** Флаг использования других переменных (формат ${VAR_NAME}) */
  uses_other_variables?: boolean;
}

/**
 * Данные для создания переменной окружения
 */
export interface EnvironmentVariableCreate {
  /** Имя переменной окружения */
  name: string;
  /** Значение переменной окружения */
  value: string;
  /** Флаг использования других переменных (формат ${VAR_NAME}) */
  uses_other_variables?: boolean;
}

/**
 * Данные для обновления переменной окружения
 */
export interface EnvironmentVariableUpdate {
  /** Имя переменной окружения */
  name: string;
  /** Значение переменной окружения */
  value: string;
  /** Флаг использования других переменных (формат ${VAR_NAME}) */
  uses_other_variables?: boolean;
}

export type ErrorResponse = {
  /** Сообщение об ошибке */
  error?: string;
};

export type GetProjectsParams = {
  /**
   * Фильтр по типу (project - обычные проекты, template - шаблоны, all - все)
   */
  type?: GetProjectsType;
};

export type GetProjectsType = (typeof GetProjectsType)[keyof typeof GetProjectsType];

export const GetProjectsType = {
  project: 'project',
  template: 'template',
  all: 'all',
} as const;

export type GetProjects200 = {
  /** @nullable */
  projects?: ProjectListItem[] | null;
};

export type CreateProject201 = {
  /** Уникальный идентификатор созданного проекта */
  id?: number;
};

export type GetProjectRuns200 = {
  /** @nullable */
  runs?: ProjectRunSummary[] | null;
};

export type CreateProjectRun201 = {
  /** Уникальный идентификатор созданного запуска */
  id?: number;
};

export type GetGlobalEnvVars200 = {
  /** @nullable */
  env_vars?: EnvironmentVariable[] | null;
};

export type CreateGlobalEnvVar201 = {
  /** Уникальный идентификатор созданной переменной */
  id?: number;
};
