/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * EasyJet API
 * API для системы непрерывной интеграции и доставки EasyJet.

EasyJet — легковесная CI/CD система для домашних серверов и пет-проектов.

## Возможности

- Управление проектами (создание, чтение, обновление)
- Запуск пайплайнов и мониторинг выполнения
- Просмотр истории запусков и логов
- Интеграция с Git

 * OpenAPI spec version: 1.0.0
 */
/**
 * Этап проекта — один шаг в пайплайне выполнения
 */
export interface ProjectStage {
  /**
   * Порядковый номер этапа (начинается с 1)
   * @minimum 1
   */
  number: number;
  /** Команда или скрипт для выполнения */
  script: string;
}

/**
 * Проект — конфигурация автоматизированного пайплайна для репозитория
 */
export interface Project {
  /** Уникальный идентификатор проекта */
  readonly id?: number;
  /** Дата и время создания проекта */
  readonly created_at?: string;
  /** Дата и время последнего изменения конфигурации */
  readonly updated_at?: string;
  /** Флаг включения автоматического расписания (cron) */
  cron_enabled?: boolean;
  /** Cron-выражение для автоматического запуска */
  cron_schedule?: string;
  /** Человеко-читаемое имя проекта */
  name: string;
  /** Локальный путь к рабочей директории проекта */
  dir?: string;
  /** URL Git-репозитория */
  git_url?: string;
  /** Имя ветки Git для сборки */
  git_branch?: string;
  /** Флаг перезапуска приложения после выполнения задачи */
  restart_after?: boolean;
  /** Количество последних запусков для хранения (0 - отключить) */
  retention_count?: number;
  /** Флаг использования переменных окружения root пользователя */
  with_root_env?: boolean;
  /**
   * Этапы пайплайна (выполняются последовательно)
   * @minItems 1
   * @nullable
   */
  stages: ProjectStage[] | null;
}

/**
 * Данные для создания нового проекта
 */
export interface ProjectCreate {
  /** Флаг включения автоматического расписания (cron) */
  cron_enabled?: boolean;
  /** Cron-выражение для автоматического запуска */
  cron_schedule?: string;
  /** Человеко-читаемое имя проекта */
  name: string;
  /** Локальный путь к рабочей директории проекта */
  dir?: string;
  /** URL Git-репозитория */
  git_url?: string;
  /** Имя ветки Git для сборки */
  git_branch?: string;
  /** Флаг перезапуска приложения после выполнения задачи */
  restart_after?: boolean;
  /** Количество последних запусков для хранения */
  retention_count?: number;
  /** Флаг использования переменных окружения root пользователя */
  with_root_env?: boolean;
  /**
   * Этапы пайплайна (выполняются последовательно)
   * @minItems 1
   */
  stages: ProjectStage[];
}

/**
 * Данные для обновления проекта
 */
export interface ProjectUpdate {
  /** Уникальный идентификатор проекта */
  id: number;
  /** Флаг включения автоматического расписания (cron) */
  cron_enabled?: boolean;
  /** Cron-выражение для автоматического запуска */
  cron_schedule?: string;
  /** Человеко-читаемое имя проекта */
  name: string;
  /** Локальный путь к рабочей директории проекта */
  dir?: string;
  /** URL Git-репозитория */
  git_url?: string;
  /** Имя ветки Git для сборки */
  git_branch?: string;
  /** Флаг перезапуска приложения после выполнения задачи */
  restart_after?: boolean;
  /** Количество последних запусков для хранения */
  retention_count?: number;
  /** Флаг использования переменных окружения root пользователя */
  with_root_env?: boolean;
  /**
   * Этапы пайплайна (выполняются последовательно)
   * @minItems 1
   */
  stages: ProjectStage[];
}

/**
 * Результат выполнения конкретного этапа запуска
 */
export interface ProjectRunStage {
  /**
   * Номер этапа
   * @minimum 1
   */
  stage_number?: number;
  /** Флаг успешного выполнения этапа */
  readonly success?: boolean;
  /** Лог выполнения этапа */
  readonly log?: string;
}

/**
 * Git-коммит, связанный с запуском
 */
export interface ProjectRunGitCommit {
  /** Порядковый номер коммита */
  number?: number;
  /** Хэш коммита в Git */
  hash?: string;
  /** Сообщение коммита (первая строка) */
  subject?: string;
}

/**
 * Запуск проекта — результат выполнения пайплайна
 */
export interface ProjectRun {
  /** Уникальный идентификатор запуска */
  readonly id?: number;
  /** Время начала запуска */
  readonly created_at?: string;
  /** Время последнего обновления статуса */
  readonly updated_at?: string;
  /** Ссылка на проект */
  readonly project_id?: number;
  /** Флаг успешного завершения всех этапов */
  readonly success?: boolean;
  /** Флаг ожидания начала выполнения */
  readonly pending?: boolean;
  /** Флаг активного выполнения */
  readonly processing?: boolean;
  /** Лог ошибки, если запуск завершился неудачей */
  readonly fail_log?: string;
  /**
   * Результаты выполнения этапов
   * @nullable
   */
  readonly stages?: readonly ProjectRunStage[] | null;
  /**
   * Git-коммиты, связанные с запуском
   * @nullable
   */
  readonly git_commits?: readonly ProjectRunGitCommit[] | null;
}

export type ErrorResponse = {
  /** Сообщение об ошибке */
  error?: string;
};

export type GetProjects200 = {
  /** @nullable */
  projects?: Project[] | null;
};

export type CreateProject201 = {
  /** Уникальный идентификатор созданного проекта */
  id?: number;
};

export type GetProjectRuns200 = {
  /** @nullable */
  runs?: ProjectRun[] | null;
};

export type CreateProjectRun201 = {
  /** Уникальный идентификатор созданного запуска */
  id?: number;
};

