/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * EasyJet API
 * API для системы непрерывной интеграции и доставки EasyJet.

EasyJet — легковесная CI/CD система для домашних серверов и пет-проектов.

## Возможности

- Управление проектами (создание, чтение, обновление)
- Запуск пайплайнов и мониторинг выполнения
- Просмотр истории запусков и логов
- Интеграция с Git

 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';

import type {
  CreateProject201,
  CreateProjectRun201,
  GetProjectRuns200,
  GetProjects200,
  Project,
  ProjectCreate,
  ProjectRun,
  ProjectUpdate,
} from './generated.schemas';

export const getEasyJetAPI = (axiosInstance: AxiosInstance = axios.default) => {
  /**
   * Возвращает список всех проектов в системе
   * @summary Получить список всех проектов
   */
  const getProjects = (options?: AxiosRequestConfig): Promise<AxiosResponse<GetProjects200>> => {
    return axiosInstance.get(`/api/v1/projects`, options);
  };

  /**
   * Создаёт новый проект с конфигурацией пайплайна
   * @summary Создать новый проект
   */
  const createProject = (
    projectCreate: ProjectCreate,
    options?: AxiosRequestConfig
  ): Promise<AxiosResponse<CreateProject201>> => {
    return axiosInstance.post(`/api/v1/projects`, projectCreate, options);
  };

  /**
   * Возвращает полную информацию о проекте по его идентификатору
   * @summary Получить информацию о проекте
   */
  const getProject = (
    projectId: number,
    options?: AxiosRequestConfig
  ): Promise<AxiosResponse<Project>> => {
    return axiosInstance.get(`/api/v1/projects/${projectId}`, options);
  };

  /**
   * Обновляет конфигурацию существующего проекта
   * @summary Обновить проект
   */
  const updateProject = (
    projectId: number,
    projectUpdate: ProjectUpdate,
    options?: AxiosRequestConfig
  ): Promise<AxiosResponse<void>> => {
    return axiosInstance.put(`/api/v1/projects/${projectId}`, projectUpdate, options);
  };

  /**
   * Возвращает список всех запусков для указанного проекта
   * @summary Получить историю запусков проекта
   */
  const getProjectRuns = (
    projectId: number,
    options?: AxiosRequestConfig
  ): Promise<AxiosResponse<GetProjectRuns200>> => {
    return axiosInstance.get(`/api/v1/projects/${projectId}/runs`, options);
  };

  /**
   * Создаёт новый запуск пайплайна для указанного проекта
   * @summary Запустить пайплайн проекта
   */
  const createProjectRun = (
    projectId: number,
    options?: AxiosRequestConfig
  ): Promise<AxiosResponse<CreateProjectRun201>> => {
    return axiosInstance.post(`/api/v1/projects/${projectId}/runs`, undefined, options);
  };

  /**
   * Возвращает детальную информацию о конкретном запуске проекта
   * @summary Получить информацию о запуске
   */
  const getProjectRun = (
    projectId: number,
    runId: number,
    options?: AxiosRequestConfig
  ): Promise<AxiosResponse<ProjectRun>> => {
    return axiosInstance.get(`/api/v1/projects/${projectId}/runs/${runId}`, options);
  };

  return {
    getProjects,
    createProject,
    getProject,
    updateProject,
    getProjectRuns,
    createProjectRun,
    getProjectRun,
  };
};
export type GetProjectsResult = AxiosResponse<GetProjects200>;
export type CreateProjectResult = AxiosResponse<CreateProject201>;
export type GetProjectResult = AxiosResponse<Project>;
export type UpdateProjectResult = AxiosResponse<void>;
export type GetProjectRunsResult = AxiosResponse<GetProjectRuns200>;
export type CreateProjectRunResult = AxiosResponse<CreateProjectRun201>;
export type GetProjectRunResult = AxiosResponse<ProjectRun>;
