// Code generated by ogen, DO NOT EDIT.

package ogenapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateProject implements createProject operation.
	//
	// Создаёт новый проект с конфигурацией пайплайна.
	//
	// POST /api/v1/projects
	CreateProject(ctx context.Context, req *ProjectCreate) (*CreateProjectCreated, error)
	// CreateProjectRun implements createProjectRun operation.
	//
	// Создаёт новый запуск пайплайна для указанного
	// проекта.
	//
	// POST /api/v1/projects/{project_id}/runs
	CreateProjectRun(ctx context.Context, params CreateProjectRunParams) (*CreateProjectRunCreated, error)
	// GetProject implements getProject operation.
	//
	// Возвращает полную информацию о проекте по его
	// идентификатору.
	//
	// GET /api/v1/projects/{project_id}
	GetProject(ctx context.Context, params GetProjectParams) (*Project, error)
	// GetProjectRun implements getProjectRun operation.
	//
	// Возвращает детальную информацию о конкретном
	// запуске проекта.
	//
	// GET /api/v1/projects/{project_id}/runs/{run_id}
	GetProjectRun(ctx context.Context, params GetProjectRunParams) (*ProjectRun, error)
	// GetProjectRuns implements getProjectRuns operation.
	//
	// Возвращает список всех запусков для указанного
	// проекта.
	//
	// GET /api/v1/projects/{project_id}/runs
	GetProjectRuns(ctx context.Context, params GetProjectRunsParams) (*GetProjectRunsOK, error)
	// GetProjects implements getProjects operation.
	//
	// Возвращает список всех проектов в системе.
	//
	// GET /api/v1/projects
	GetProjects(ctx context.Context) (*GetProjectsOK, error)
	// UpdateProject implements updateProject operation.
	//
	// Обновляет конфигурацию существующего проекта.
	//
	// PUT /api/v1/projects/{project_id}
	UpdateProject(ctx context.Context, req *ProjectUpdate, params UpdateProjectParams) error
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
